### ISSUE TITLE
kiwi logger can not be used with LML Basic Template

### ISSUE THREAD

**Issue by roleyzhang** [czyzby/gdx-lml#83]
Hi,
I used gdx-setup to create my testing project, I selected Kiwi from Third-party and select LML Basic from Templates. Then I import com.github.czyzby.kiwi.log.Logger; and import com.github.czyzby.kiwi.log.LoggerService; in my class and use it "private final Logger logger = LoggerService.forClass(gnk.class);¬ ". When I run my code there has a java.lang.NullPointerException. the error message is:desktop:runException in thread "main" java.lang.ExceptionInInitializerError                                                 
        at citrine.gnk.gnk.<init>(gnk.java:21)
        at citrine.gnk.desktop.DesktopLauncher.createApplication(DesktopLauncher.java:15)                                    
        at citrine.gnk.desktop.DesktopLauncher.main(DesktopLauncher.java:11)                                                 
Caused by: java.lang.NullPointerException
        at com.github.czyzby.kiwi.log.LoggerService.<init>(LoggerService.java:38)                                            
        at com.github.czyzby.kiwi.log.LoggerService.<clinit>(LoggerService.java:24)                                          
        ... 3 more

I don't known what cause it, I used the kiwi logger successful with Autumn MVC Template.

**Comment by czyzby** [comment]
`LoggerService` turns on LibGDX logging in the constructor:

```java
Gdx.app.setLogLevel(Application.LOG_DEBUG);
```

It basically references `Gdx.app` before it is initiated. For now, you should import and use the logger after the application is created.
